#!/bin/bash
#--------------------------------------------------------
#   This script is used for instalation theme rgb xderm
#   Script by helmiau a.k.a Helmi Amirudin
#--------------------------------------------------------

RED='\033[0;31m'
BLU='\033[1;34m'
YEL='\033[1;33m'
GRE='\033[1;32m'
NOR='\033[0;37m'

USERNOW=$(grep user /root/auth.txt | sed 's/.*user=//')
PASSNOW=$(grep passwd /root/auth.txt | sed 's/.*passwd=//')
LOGINOW=$(if [ -e /www/xderm/login.php ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
LOGINOWBAK=$(if [ -e /www/xderm/login.php.xdrtool ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
URL="https://raw.githubusercontent.com/putra190/xdrtheme-rgb/main"
echo "==========================================="
echo -e "|       ${BLU} Installation RGB${YEL}THEME ${GRE}by Adi-Putra${NOR}       |"
echo "===========================================${GRE}"
echo "  Install Theme for Xderm         = 1"
echo "  Install Theme for Libernet      = 2"
echo -e "${NOR}==========================================="
echo "  Exit = type anything !"
echo "==========================================="
echo ""
echo -n "  Enter Your Option : " 
read -r jawab
echo "==========================================="
clear
bash installer-rgb
if [[ $jawab == "1" ]]; then
echo "==========================================="
echo -e " Installing RGB Theme by ADI-PUTRA"
echo "=========================================="
url="https://raw.githubusercontent.com/putra190/xdrtheme-rgb/main"
wget -O /www/xderm/img/ico.png --no-check-certificate $url/img/ico.png
wget -O /www/xderm/img/image.png --no-check-certificate $url/img/image.png
wget -O /www/xderm/img/background.jpg --no-check-certificate $url/img/background.jpg
wget -O /www/xderm/index.php --no-check-certificate $url/index.php
wget -O /www/xderm/login.php --no-check-certificate $url/login.php
wget -O /www/xderm/login.html --no-check-certificate $url/login.html
wget -O /www/xderm/addon.php --no-check-certificate $url/addon.php
mkdir /www/xderm/css
chmod 777 /www/xderm/css
wget -O /www/xderm/css/login.css --no-check-certificate $url/css/login.css
wget -O /www/xderm/css/style.css --no-check-certificate $url/css/style.css
wget -O /www/xderm/css/theme.css --no-check-certificate $url/css/theme.css
echo "==========================================="
echo -e " Installation finished !"
echo "==========================================="
clear
bash installer-rgb
else
echo " Exiting program !"
echo "==========================================="
exit
fi
